### ISSUE TITLE
Stability of MLJFlux.jl API

### ISSUE THREAD

**Issue by bkamins** [FluxML/MLJFlux.jl#151]
I am planning to include MLJFlux.jl in a book. Therefore my question is how stable do you expect the API to be?

(for a future reference the question is asked at the time of 0.1.15 release)

**Comment by ablaom** [comment]
That's a good question. Having MLJFlux in a book is an exciting prospect.

I think that changes that might have been breaking - around the "builder" concept for example - are unlikely to change at this late stage. 

There was an unusually long gestation period before the first release, for we knew all those enthusiastic Flux users were likely to have high expectations and give the package a lot of suspicious scrutiny 😄 . And we have not made any breaking release since 0.1. 

I personally do not have anything planned that would break the API, or am aware of any other such plans. @ayush-1506 may like to comment. 

A small reservation is that, given the number of issues raised, user-testing is in a relatively early stage. But it's hard to say for sure. 

I doubt there is anything comparable with the same maturity, although you should check out the FastAPI.jl project if you have not already done so. And you may find [this](https://discourse.julialang.org/t/pros-and-cons-of-using-flux-directly-over-using-mlj-mljflux/59756) discussion relevant.

**Comment by bkamins** [comment]
Thank you of a detailed answer!
